apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
  selector:
    app: mongo-app
  clusterIP: None

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        livenessProbe:
            exec:
             command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"              
            initialDelaySeconds: 30 
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
        
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim